version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: carservice
      MYSQL_USER: yaqout
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
